# NumPy & Pandas

In [2]:
import numpy as np 
import pandas as pd

## NumPy

**Numpy Arrays**

In [30]:
int_array = np.array([1,2,3,4,5])
print(int_array)
float_array = np.array([3.14, 2.71, 1.61, 1.41, 1.21])
print(float_array)
string_array = np.array(['a', 'b', 'c', 'd', 'e'])
print(string_array)

# create a numpy array using arange
range_array = np.arange(1, 6)
print(range_array)

# create a numpy array using randint
randint_array = np.random.randint(1, 10, size=(5))
print(randint_array)

# info about an array
print(f'Size: {string_array.size}')

# indexes
print(f'First element: {float_array[0]}')
print(f'Last element: {float_array[-1]}')

# update an array
int_array[0] = 10
print(int_array)

# slicing
print(f'First three elements: {float_array[:3]}')

# copy an array
array_copy = float_array.copy()
print(array_copy)

# array concatenation
array_concat = np.concatenate((int_array, [6,7,8,9,10]))
print(array_concat)

print(string_array.size)

[1 2 3 4 5]
[3.14 2.71 1.61 1.41 1.21]
['a' 'b' 'c' 'd' 'e']
[1 2 3 4 5]
[9 7 9 7 1]
Size: 5
First element: 3.14
Last element: 1.21
[10  2  3  4  5]
First three elements: [3.14 2.71 1.61]
[3.14 2.71 1.61 1.41 1.21]
[10  2  3  4  5  6  7  8  9 10]
5

**using arithmetic operators with numpy arrays**

In [4]:
x = np.arange(10)
print(x)

# add 5 to each element
print(x + 5)

# multipy each element by 10
print(x * 10)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[ 0 10 20 30 40 50 60 70 80 90]

**Numpy array functions**

In [5]:
print(np.power(x, 2))
print(np.max(x))
print(np.min(x))
print(np.mean(x))

[ 0  1  4  9 16 25 36 49 64 81]
9
0
4.5

**Array sorting**

In [6]:
# sort an array as a copy
print(np.sort(float_array))

# sort an array in place
float_array.sort()
print(float_array)

[1.21 1.41 1.61 2.71 3.14]
[1.21 1.41 1.61 2.71 3.14]

## Pandas

**Series**

In [32]:
# pandas series
series = pd.Series([1,2,3,4,5])
print(series)

# pandas series with custom index, built from a dictionary
spanish_nums = {'one': 'uno', 'two': 'dos', 'three': 'tres', 
                'four': 'cuatro', 'five': 'cinco'}
spanish_nums_series = pd.Series(spanish_nums)
print(spanish_nums_series)

one         uno
two         dos
three      tres
four     cuatro
five      cinco
dtype: object

**DataFrames**

In [8]:
states_areas = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995})
states_pop = pd.Series({'California': 38332521, 'Texas': 26448193, 
                        'New York': 19651127, 'Illinois': 12882135, 'Florida': 19552860})

states_df = pd.DataFrame({'area': states_areas, 
                          'population': states_pop})
states_df

              area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [27]:
states_df.head(2)

              area  population
California  423967    38332521
Florida     170312    19552860

In [12]:
states_df['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [13]:
states_df.area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [22]:
states_df.values

array([[  423967, 38332521],
       [  170312, 19552860],
       [  149995, 12882135],
       [  141297, 19651127],
       [  695662, 26448193]], dtype=int64)

In [21]:
states_df.loc['New York']

area            141297
population    19651127
Name: New York, dtype: int64

In [20]:
states_df.iloc[0]

area            423967
population    38332521
Name: California, dtype: int64

In [23]:
# numpy missing value
np.nan

nan

## Reading a CSV into a DataFrame

In [24]:
# import csv file as a pandas dataframe
df = pd.read_csv('data/grading_scheme.csv')
df.head()

  Letter Grade Percentage Range  Value Description
0            A           90-100    4.0   Excellent
1           A-           90-100    3.7   Excellent
2           B+            80-89    3.3        Good
3            B            80-89    3.0        Good
4           B-            80-89    2.7        Good

In [29]:
# import csv file setting the first column as the index
df = pd.read_csv('data/grading_scheme.csv', index_col=0)
df.head()

             Percentage Range  Value Description
Letter Grade
A                      90-100    4.0   Excellent
A-                     90-100    3.7   Excellent
B+                      80-89    3.3        Good
B                       80-89    3.0        Good
B-                      80-89    2.7        Good